### ISSUE TITLE
Integrate to the project angular material and flex-layout 

### ISSUE THREAD

**Issue by wil92** [dcs-community/dcs-frontend#4]
In order to be more efficient, it is better to use the angular set of components and modify globally the styles with the design we decide to use in the blog

take a look at the [Angular Material library](https://material.angular.io/)

Integrate Flex-Layout library in the project. This is a good library for responsive design and came in substitution of the popular bootstraps columns way

take a look at the [Flex-Layout library](https://github.com/angular/flex-layout/wiki/API-Documentation)

**Comment by KhozmoS** [comment]
I just installed the Material & Flex layout libraries as the respective guide said , with the most simplest configuration.

**Comment by wil92** [comment]
seam good to me, remember to assign the issue to your account when you are working on it
