### ISSUE TITLE
Create blog header component

### ISSUE THREAD

**Issue by wil92** [dcs-community/dcs-frontend#5]
It depends on the design, but basically is use the angular material component and update the styles to the new design

First proposal of header for the blog
![image](https://user-images.githubusercontent.com/10768089/70246952-d2e5a080-1778-11ea-8587-54561585d128.png)

**Comment by KhozmoS** [comment]
For me a simple header like that is fine , just adding to it a logging and a couple of navigation link will be enough.

**Comment by wil92** [comment]
in order to not overwork, remember to use the component of angular for that. It is just use the component and change the styles
